function plot_eigenfunctions(k, figure_no, results, p, q, r, M, rho, filename)
    [a, ~] = numSubplots(k);
    for i = 1:k
        figure(figure_no)
        subplot(a(1), a(2), i)
        plot_eigenfunction(i, results, r, M, rho)
    end
    s = ['Eigenfunctions for $p$ = ' num2str(p)...
        ' , $q$ = ' num2str(q) ...
        ' , $r$ = ' num2str(r) ...
        ' , $k$ = ' num2str(k)];
    sgtitle(s, 'Interpreter', 'Latex', 'Fontsize', 14);
    saveas(figure(figure_no),[pwd, '/res_images/', filename, ...
        '/eigenfunctions_p_', erase(num2str(p), '.')...
        '_q_', erase(num2str(q), '.'), ...
        '_r_', erase(num2str(r), '.'), ...
        '.fig']);
end