function plot_clusters(clusters, figure_no, filename, ...
    p, q, r, k, K, ...
    experiment, TA, CA ...
)
    figure(figure_no);
    imagesc(clusters); 
    colormap(jet); 
    c = colorbar; 
    ylabel(c, 'Cluster Index' , 'Interpreter', 'Latex', 'Fontsize', 14)
    if ~exist('experiment','var')
        s = ['Segmentation using $p$ = ' num2str(p)...
            ' , $q$ = ' num2str(q) ...
            ' , $r$ = ' num2str(r) ...
            ' , $k$ = ' num2str(k) ...
            ' , $K$ = ' num2str(K-1)];
        title(s, 'Interpreter', 'Latex', 'Fontsize', 14);
        saveas(figure(figure_no),[pwd, '/res_images/', filename, ...
            '/clusters_p_', erase(num2str(p), '.')...
            '_q_', erase(num2str(q), '.'), ...
            '_r_', erase(num2str(r), '.'), ...
            '.fig']);
    elseif ~experiment
        s = ['$p$ = ' num2str(p)...
            ' , $q$ = ' num2str(q) ...
            ' , $r$ = ' num2str(r) ...
            ' , $k$ = ' num2str(k) ...
            ' , $K$ = ' num2str(K-1) ...
            ' ; (TA, CA) = (' num2str(round(TA, 2)) ','...
            num2str(round(CA, 2)) ')'];
        title(s, 'Interpreter', 'Latex', 'Fontsize', 14);
        saveas(figure(figure_no),[pwd, '/res_images/', filename, ...
            '/clusters_p_', erase(num2str(p), '.')...
            '_q_', erase(num2str(q), '.'), ...
            '_r_', erase(num2str(r), '.'), ...
            '.fig']);
    else
        s = ['(TA, CA) = (' num2str(round(TA, 2)) ','...
            num2str(round(CA, 2)) ')'];
        title(s, 'Interpreter', 'Latex', 'Fontsize', 14);
    end
end